apiVersion: v1
kind: Namespace
metadata:
  name: k3stest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: k3stest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ghcr.io/qzblue/k3stest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: k3stest
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
